# Working code commented to test workflow call from repo A to repo B 26 11 25


# name: Build and Deploy UI

# on:
#   pull_request:
#     branches: [ main ]
#   push:
#     branches: [ main ]

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout source
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install dependencies
#         run: |
#           cd angular-git-int
#           npm install

#       - name: Build project
#         run: |
#           cd angular-git-int
#           npm run build

#       # Deploy only when pushing/merging into main
#       - name: Deploy to GitHub Pages
#         if: github.event_name == 'push'
#         run: |
#           cd angular-git-int
#           npm run deploy-ui

#       - name: Show trigger
#         run: echo "Triggered by ${{ github.event_name }}"
