name: Handle Token Update

on:
  repository_dispatch:
    types: [tokens-updated]

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: false
        default: 'main'
      environment:
        description: 'Environment to deploy'
        required: false
        default: 'staging'

jobs:
  update-tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd angular-git-int
          npm install

      - name: Download tokens from Repo A
        run: |
          mkdir -p angular-git-int/tokens
          curl -L https://raw.githubusercontent.com/ashishsg444/design-token/main/core.json \
            -o angular-git-int/tokens/core.json
          # Add more curl commands here if you have multiple token files

      - name: Run token transform script
        run: |
          cd angular-git-int
          npm run build:tokens

      - name: Stage all changes
        run: |
          git add .

      - name: Debug staged changes
        run: |
          git status --short
          git diff --stat

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: update-design-tokens-${{ github.run_id }}
          title: "chore: update design tokens"
          body: "This PR updates design tokens and regenerates CSS/SCSS files using build:tokens."
          commit-message: "chore: update design tokens and regenerate CSS/SCSS"
